name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.9, '3.10', '3.11', '3.12']
    steps:
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Fetch lonelypst
        uses: actions/checkout@v4
      - name: Generic python setup
        run: |
          python -m pip install --upgrade pip
      - name: Installing dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Lint lonelypst with black
        run: |
          python -m black --check src/lonelypst
      - name: Type check lonelypst with mypy
        working-directory: src
        run: |
          mypy lonelypst --explicit-package-bases --disallow-untyped-defs
      - name: Lint lonelypst with ruff
        run: ruff check --output-format=github src
      - name: Run gencluster tests
        working-directory: src
        run: |
          python -m lonelypst.tests.gencluster
